
services:
  nextjs:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - RESEND_API_KEY=${RESEND_API_KEY}
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run ivoneth-banqueteria2
    volumes:
      - ./cloudflared:/etc/cloudflared
    depends_on:
      - nextjs
    restart: unless-stopped
